name: insight
description: "INSIGHT – High School Sports Growth App"
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter


  # 基本UIライブラリ
  cupertino_icons: ^1.0.8
  intl: ^0.20.2

  # 状態管理
  provider: ^6.1.2

  # HTTP通信
  http: ^1.2.1

  # 永続化（ログイン保持用）
  shared_preferences: ^2.2.3

  # アニメーション・UI補助
  flutter_animate: ^4.5.0
  carousel_slider: ^4.2.1

  # JSONシリアライズ
  json_annotation: ^4.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.8
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true

  assets:
    - assets/
